# Generated by Django 4.0.1 on 2022-02-28 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_order_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
